### PR TITLE
Add lint-staged

### PR DESCRIPTION
**Pull request by glennreyes**
Adds lint-staged (https://github.com/kitze/sizzy/issues/13) and ran prettier through js files in `src`.

### CODE REVIEW

**Comment by kitze** [comment]
@glennreyes Have I told you you're amazing? Thanks for this 👊👊👊👊

I didn't see this PR so now it has conflicts 😞

One thing i would change: no trailing commas, hate them 😅
One thing i would add: running tests before a commit? Makes sense?

**Comment by SaraVieira** [comment]
@kize I think it makes much sense mainly in open source projects.

Are you using flow?

**Comment by glennreyes** [comment]
@kitze Not sure why CI is failing, I get 404. Can you jump in?

**Comment by kitze** [comment]
@glennreyes I see this in the netlify logs:

```
7:20:43 PM: ● Test suite failed to run

Couldn't find preset "es2015" relative to directory "/opt/build/repo"
```

Hmm...

**Comment by kitze** [comment]
Getting the same error @glennreyes 

```
7:55:49 PM: yarn test v0.18.1
7:55:49 PM: $ jest -i 
7:55:50 PM: FAIL __tests__/utils/url-utils.spec.js
7:55:51 PM: ● Test suite failed to run

Couldn't find preset "es2015" relative to directory "/opt/build/repo"

at node_modules/babel-core/lib/transformation/file/options/option-manager.js:298:19
at Array.map (native)
at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:20)
at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:258:10)
at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:243:14)
at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:373:12)
at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:221:65)
at new File (node_modules/babel-core/lib/transformation/file/index.js:141:24)
at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)


```

**Comment by glennreyes** [comment]
@kitze Can you purge cache at netlify? Tests are passing on local machine

**Comment by kitze** [comment]
@glennreyes You cannot purge cache for a deploy on a branch on Netlify, so I just merged it. It should build on master now. 

Thank you!

**Comment by kitze** [comment]
@glennreyes ok that was a bad idea 😅 Same error on master.

**Comment by kitze** [comment]
Maybe this is the problem? https://github.com/facebookincubator/create-react-app/issues/949

**Comment by glennreyes** [comment]
Looks like! Can you move babel settings to package.json?

**Comment by glennreyes** [comment]
Dough, you already did! 😆

**Comment by kitze** [comment]
@glennreyes tried that, doesn't work. Uuughhh, so frustrating! Maybe the version of node is the problem?

**Comment by glennreyes** [comment]
@kitze Did you try to install `babel-preset-es2015 `? Or wanna move to `babel-preset-env`? 😛

**Comment by glennreyes** [comment]
@kitze I can open another PR if you want

**Comment by kitze** [comment]
@glennreyes i'm trying to install the babel presets and plugins

**Pull request merged**
